/**
 * POST /api/reset-password   — public. Apply a new password using a valid
 *   single-use reset token (generated by a super-admin, Modo B).
 *   body: { token, password }
 */
import type { APIRoute } from 'astro';
import { and, eq, gt, isNull } from 'drizzle-orm';
import { getDb, schema } from '@lib/db';
import { setPasswordForUser, hashToken } from '@lib/admin/password';

export const prerender = false;

export const POST: APIRoute = async ({ request, locals }) => {
  const body = (await request.json().catch(() => null)) as {
    token?: string;
    password?: string;
  } | null;

  const token = body?.token ?? '';
  const password = body?.password ?? '';
  if (!token) return Response.json({ error: 'Token faltante.' }, { status: 400 });
  if (password.length < 10)
    return Response.json({ error: 'La contraseña debe tener al menos 10 caracteres.' }, { status: 400 });

  const env = locals.runtime.env;
  const db = getDb(env);
  const tokenHash = await hashToken(token);

  // Valid = matching hash, not yet used, not expired.
  const [row] = await db
    .select()
    .from(schema.passwordResetTokens)
    .where(
      and(
        eq(schema.passwordResetTokens.tokenHash, tokenHash),
        isNull(schema.passwordResetTokens.usedAt),
        gt(schema.passwordResetTokens.expiresAt, new Date()),
      ),
    );

  if (!row)
    return Response.json({ error: 'El enlace es inválido o ha expirado.' }, { status: 400 });

  const ok = await setPasswordForUser(env, row.userId, password);
  if (!ok)
    return Response.json(
      { error: 'No se pudo actualizar la contraseña de la cuenta.' },
      { status: 400 },
    );

  // Mark single-use.
  await db
    .update(schema.passwordResetTokens)
    .set({ usedAt: new Date() })
    .where(eq(schema.passwordResetTokens.id, row.id));

  return Response.json({ ok: true });
};
